import pathlib
p = pathlib.Path(r'C:\Users\hemat\oturkish-kebab\index.html')
html = p.read_text(encoding='utf-8')

new_css = r"""
    :root{--black:#111;--white:#fff;--grey:#666;--light-grey:#888;--line:#e5e5e5;--bg:#fafafa}
    *{box-sizing:border-box}html{scroll-behavior:smooth;-webkit-text-size-adjust:100%}body{margin:0;background:var(--white);color:var(--black);font:16px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;text-rendering:optimizeLegibility;-webkit-tap-highlight-color:transparent}a{color:inherit;text-decoration:none}button{font:inherit;color:inherit;-webkit-tap-highlight-color:transparent}h1,h2,h3,p{margin:0}h1,h2,h3{font-weight:600;letter-spacing:-.02em}
    .wrap{width:min(1060px,calc(100% - 32px));margin:auto}@media(min-width:768px){.wrap{width:min(1060px,calc(100% - 48px))}}
    .notice{text-align:center;padding:9px 12px;background:var(--black);color:var(--white);font-size:10px;font-weight:500;letter-spacing:.08em;text-transform:uppercase;line-height:1.4}@media(min-width:768px){.notice{padding:10px 16px;font-size:11px}}
    header{position:sticky;top:0;z-index:10;background:rgba(255,255,255,.96);border-bottom:1px solid var(--line);backdrop-filter:saturate(1.4) blur(10px);-webkit-backdrop-filter:saturate(1.4) blur(10px)}
    .nav{display:flex;align-items:center;justify-content:space-between;min-height:58px;gap:12px;flex-wrap:nowrap}@media(min-width:768px){.nav{min-height:64px;gap:24px}}
    .brand{flex-shrink:0;display:flex;align-items:center;gap:10px;font-size:15px;font-weight:700;letter-spacing:-.01em;line-height:1}.brand small{display:block;margin-top:3px;color:var(--light-grey);font-size:9px;font-weight:400;letter-spacing:.14em;text-transform:uppercase}
    .navlinks{display:none;gap:20px;color:var(--grey);font-size:13px;align-items:center}@media(min-width:900px){.navlinks{display:flex;gap:26px}}.navlinks a{transition:color 150ms ease;white-space:nowrap;padding:6px 0}.navlinks a:hover{color:var(--black)}
    .nav-actions{display:flex;align-items:center;gap:8px;flex-shrink:0}@media(min-width:768px){.nav-actions{gap:12px}}
    .call{display:none;padding:9px 14px;border:1px solid var(--black);border-radius:2px;background:var(--black);color:var(--white);font-size:11px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;transition:all 150ms ease;white-space:nowrap}@media(min-width:900px){.call{display:inline-flex;align-items:center;justify-content:center}}@media(min-width:1100px){.call{padding:9px 16px;font-size:12px}}.call:hover{background:var(--white);color:var(--black)}
    .toggle{display:inline-grid;place-items:center;width:40px;height:40px;border:1px solid transparent;border-radius:2px;background:none;font-size:20px;line-height:1;cursor:pointer;transition:border-color 150ms ease,background 150ms ease;flex-shrink:0}@media(min-width:900px){.toggle{display:none}}.toggle:hover{border-color:var(--line);background:var(--bg)}.toggle:active{background:var(--line)}
    .hero{padding:48px 0 44px;border-bottom:1px solid var(--line)}@media(min-width:600px){.hero{padding:72px 0 60px}}@media(min-width:768px){.hero{padding:90px 0 78px}}@media(min-width:1024px){.hero{padding:110px 0 90px}}
    .eyebrow{color:var(--light-grey);font-size:10px;font-weight:500;letter-spacing:.18em;text-transform:uppercase;line-height:1.5}@media(min-width:768px){.eyebrow{font-size:11px}}
    .hero h1{max-width:640px;margin-top:16px;font-size:clamp(1.9rem,8vw,4.2rem);line-height:1.05;letter-spacing:-.03em}@media(min-width:768px){.hero h1{margin-top:22px}}
    .lead{max-width:520px;margin-top:16px;color:var(--grey);font-size:15px;line-height:1.6}@media(min-width:768px){.lead{margin-top:24px;font-size:16px;line-height:1.65}}
    .actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:24px}@media(min-width:768px){.actions{gap:12px;margin-top:36px}}
    .btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 18px;border:1px solid var(--black);border-radius:2px;font-size:12px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;cursor:pointer;transition:all 150ms ease;white-space:nowrap;touch-action:manipulation}@media(min-width:768px){.btn{min-height:46px;padding:0 24px}}.btn.primary{background:var(--black);color:var(--white)}.btn.primary:hover{background:var(--white);color:var(--black)}.btn.primary:active{transform:scale(.98)}.btn.outline{background:transparent;color:var(--black)}.btn.outline:hover{background:var(--black);color:var(--white)}
    .availability{margin-top:20px;color:var(--light-grey);font-size:12px;letter-spacing:.04em;line-height:1.5}@media(min-width:768px){.availability{margin-top:28px}}.availability strong{color:var(--black);font-weight:600}
    section{padding:48px 0}@media(min-width:600px){section{padding:60px 0}}@media(min-width:768px){section{padding:72px 0}}@media(min-width:1024px){section{padding:90px 0}}
    .head{margin-bottom:32px}@media(min-width:768px){.head{margin-bottom:44px}}.kicker{color:var(--light-grey);font-size:10px;font-weight:500;letter-spacing:.18em;text-transform:uppercase}@media(min-width:768px){.kicker{font-size:11px}}.head h2{margin-top:10px;font-size:clamp(1.5rem,4vw,2.5rem);line-height:1.1;letter-spacing:-.02em}@media(min-width:768px){.head h2{margin-top:12px}}.intro{max-width:440px;margin-top:10px;color:var(--grey);font-size:13px;line-height:1.6}@media(min-width:768px){.intro{margin-top:14px;font-size:14px}}
    .tabs{display:flex;gap:18px;border-bottom:1px solid var(--line);margin-bottom:8px;overflow-x:auto;overflow-y:hidden;-webkit-overflow-scrolling:touch;scrollbar-width:none;flex-wrap:nowrap;padding-bottom:1px}.tabs::-webkit-scrollbar{display:none}@media(min-width:768px){.tabs{gap:24px;overflow:visible;flex-wrap:wrap}}
    .tab{position:relative;flex:0 0 auto;border:0;background:none;color:var(--light-grey);padding:0 0 14px;cursor:pointer;font-size:12.5px;font-weight:500;letter-spacing:.04em;text-transform:uppercase;transition:color 150ms ease;white-space:nowrap;touch-action:manipulation;min-height:44px;display:inline-flex;align-items:center}@media(min-width:768px){.tab{font-size:13px;min-height:auto}}.tab:hover,.tab[aria-selected=true]{color:var(--black)}.tab[aria-selected=true]:after{content:'';position:absolute;left:0;right:0;bottom:-1px;height:2px;background:var(--black)}@media(min-width:768px){.tab[aria-selected=true]:after{height:1px}}
    .menu{display:grid;grid-template-columns:1fr;gap:0}@media(min-width:640px){.menu{grid-template-columns:1fr 1fr;column-gap:32px}}@media(min-width:1024px){.menu{column-gap:48px}}@media(min-width:1100px){.menu{column-gap:56px}}
    .item{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid var(--line)}@media(min-width:600px){.item{gap:18px;padding:18px 0}}.item h3{font-size:14px;font-weight:600;line-height:1.3}@media(min-width:768px){.item h3{font-size:15px}}.item p{margin-top:3px;color:var(--grey);font-size:12.5px;line-height:1.5;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}@media(min-width:768px){.item p{margin-top:4px;font-size:13px;-webkit-line-clamp:unset;overflow:visible}}.price{font-size:13px;font-weight:600;text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums;flex-shrink:0}@media(min-width:768px){.price{font-size:14px}}.price small{display:block;margin-top:2px;color:var(--light-grey);font-size:10.5px;font-weight:400}@media(min-width:768px){.price small{font-size:11px}}
    .item.has-thumb{grid-template-columns:64px 1fr auto;gap:10px}@media(min-width:400px){.item.has-thumb{grid-template-columns:72px 1fr auto;gap:12px}}@media(min-width:600px){.item.has-thumb{grid-template-columns:92px 1fr auto;gap:18px}}
    .item-thumb{width:64px;height:48px;object-fit:cover;border-radius:4px;border:1px solid var(--line);background:var(--bg);display:block}@media(min-width:400px){.item-thumb{width:72px;height:54px}}@media(min-width:600px){.item-thumb{width:92px;height:68px}}
    .feature{background:var(--bg);border-block:1px solid var(--line)}.feature-layout{display:grid;grid-template-columns:1fr;gap:28px}@media(min-width:768px){.feature-layout{gap:36px}}@media(min-width:900px){.feature-layout{grid-template-columns:.85fr 1.15fr;gap:48px}}@media(min-width:1100px){.feature-layout{grid-template-columns:.8fr 1.2fr;gap:64px}}
    .feature-copy{max-width:60ch;color:var(--grey);font-size:15px;line-height:1.65}@media(min-width:768px){.feature-copy{font-size:17px}}.feature-copy p+p{margin-top:16px}@media(min-width:768px){.feature-copy p+p{margin-top:20px}}
    .facts{display:grid;grid-template-columns:1fr;gap:20px;margin-top:32px}@media(min-width:500px){.facts{grid-template-columns:repeat(2,1fr);gap:24px}}@media(min-width:768px){.facts{gap:32px;margin-top:48px}}
    .fact{border-left:2px solid var(--black);padding-left:14px}@media(min-width:768px){.fact{padding-left:18px;border-left-width:1px}}.fact strong{display:block;font-size:10.5px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;line-height:1.3}@media(min-width:768px){.fact strong{font-size:11px}}.fact span{display:block;margin-top:6px;color:var(--grey);font-size:12.5px;line-height:1.55}@media(min-width:768px){.fact span{margin-top:8px;font-size:13px}}
    .visit-card{padding:22px;border:1px solid var(--line);background:var(--white);border-radius:2px}@media(min-width:600px){.visit-card{padding:28px}}@media(min-width:768px){.visit-card{padding:36px}}
    .visit-card h3{font-size:19px}@media(min-width:768px){.visit-card h3{font-size:22px}}.visit-card>p{margin-top:8px;color:var(--grey);font-size:14px;line-height:1.5}@media(min-width:768px){.visit-card>p{margin-top:10px}}
    .contact-grid{display:grid;grid-template-columns:1fr;gap:0;margin-top:20px}@media(min-width:520px){.contact-grid{grid-template-columns:1fr 1fr;gap:0 20px}}@media(min-width:768px){.contact-grid{gap:0 24px;margin-top:30px}}
    .contact{padding:12px 0;border-top:1px solid var(--line)}@media(min-width:768px){.contact{padding:14px 0}}.contact label{display:block;color:var(--light-grey);font-size:9.5px;font-weight:500;letter-spacing:.14em;text-transform:uppercase}@media(min-width:768px){.contact label{font-size:10px}}.contact strong{display:block;margin-top:4px;font-size:13px;font-weight:500;letter-spacing:-.01em}@media(min-width:768px){.contact strong{margin-top:5px;font-size:14px}}
    .phones{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}@media(min-width:768px){.phones{gap:10px;margin-top:26px}}.phone{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 14px;border:1px solid var(--black);border-radius:2px;font-size:12.5px;font-weight:600;transition:all 150ms ease;flex:1 1 auto;min-width:calc(50% - 4px);text-align:center}@media(min-width:480px){.phone{flex:0 1 auto;min-width:auto}}@media(min-width:768px){.phone{min-height:40px;padding:0 16px;font-size:13px}}.phone:hover{background:var(--black);color:var(--white)}
    .price{display:flex;flex-direction:column;align-items:flex-end;gap:2px}.add{display:inline-grid;place-items:center;width:28px;height:28px;margin-bottom:3px;border:1px solid var(--black);border-radius:2px;background:none;font-size:16px;line-height:1;cursor:pointer;transition:all 150ms ease;touch-action:manipulation}@media(min-width:768px){.add{width:26px;height:26px;margin-bottom:4px}}.add:hover{background:var(--black);color:var(--white)}.add:active{transform:scale(.92)}.add.pulse{animation:pulse 350ms ease}.badge.bump{animation:bump 300ms ease}@keyframes pulse{0%{transform:scale(1)}40%{transform:scale(1.25);background:var(--black);color:var(--white)}100%{transform:scale(1)}}@keyframes bump{0%{transform:scale(1)}50%{transform:scale(1.4)}100%{transform:scale(1)}}
    .cart-toggle{position:relative;display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border:1px solid var(--line);border-radius:2px;background:none;font-size:11px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;cursor:pointer;transition:border-color 150ms ease,background 150ms ease;white-space:nowrap;min-height:40px;touch-action:manipulation}@media(min-width:768px){.cart-toggle{gap:8px;padding:9px 14px;font-size:12px}}.cart-toggle:hover{border-color:var(--black);background:var(--bg)}
    .badge{display:inline-grid;place-items:center;min-width:18px;height:18px;padding:0 4px;border-radius:999px;background:var(--black);color:var(--white);font-size:10px;font-weight:700;line-height:1}@media(min-width:768px){.badge{min-width:17px;height:17px}}
    .backdrop{position:fixed;inset:0;z-index:30;background:rgba(17,17,17,.45);backdrop-filter:blur(2px);-webkit-backdrop-filter:blur(2px);opacity:0;pointer-events:none;transition:opacity 200ms ease}.backdrop.show{opacity:1;pointer-events:auto}
    .drawer{position:fixed;top:0;right:0;bottom:0;z-index:31;width:min(420px,100%);max-width:100vw;background:var(--white);border-left:1px solid var(--line);display:flex;flex-direction:column;transform:translateX(100%);transition:transform 260ms cubic-bezier(.32,.72,0,1)}.drawer.open{transform:none}
    .drawer-head{display:flex;align-items:center;justify-content:space-between;padding:16px 16px;border-bottom:1px solid var(--line);min-height:56px}@media(min-width:768px){.drawer-head{padding:20px 22px}}.drawer-head strong{font-size:14px}.x-btn{border:0;background:none;font-size:22px;line-height:1;cursor:pointer;color:var(--grey);padding:6px;width:40px;height:40px;display:grid;place-items:center;border-radius:2px;transition:color 150ms ease,background 150ms ease}.x-btn:hover{color:var(--black);background:var(--bg)}
    .drawer-body{flex:1;overflow:auto;padding:4px 16px}@media(min-width:768px){.drawer-body{padding:6px 22px}}.ditem{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)}@media(min-width:768px){.ditem{gap:14px;padding:14px 0}}.ditem strong{font-size:13px;font-weight:600}@media(min-width:768px){.ditem strong{font-size:14px}}.ditem .unit{display:block;margin-top:4px;color:var(--light-grey);font-size:12px;display:flex;align-items:center;gap:6px;flex-wrap:wrap}
    .mini{width:28px;height:28px;border:1px solid var(--line);border-radius:2px;background:none;cursor:pointer;line-height:1;font-size:13px;display:inline-grid;place-items:center;transition:border-color 150ms ease,background 150ms ease;touch-action:manipulation}@media(min-width:768px){.mini{width:22px;height:22px}}.mini:hover{border-color:var(--black)}.mini:active{background:var(--black);color:var(--white)}
    .empty{color:var(--light-grey);font-size:13px;text-align:center;padding:32px 0}.drawer-foot{padding:16px;border-top:1px solid var(--line);background:var(--white)}@media(min-width:768px){.drawer-foot{padding:20px 22px}}.total{display:flex;justify-content:space-between;align-items:center;font-size:15px;font-weight:600;margin-bottom:12px}@media(min-width:768px){.total{margin-bottom:14px}}.pay{width:100%;min-height:46px}.pay:disabled{opacity:.35;cursor:not-allowed}.note{margin-top:10px;color:var(--light-grey);font-size:11px;text-align:center;line-height:1.5}
    footer{padding:24px 0;border-top:1px solid var(--line)}@media(min-width:768px){footer{padding:34px 0}}.footer{display:flex;flex-direction:column;gap:12px;color:var(--light-grey);font-size:11px;line-height:1.5}@media(min-width:600px){.footer{flex-direction:row;align-items:center;justify-content:space-between;gap:24px;font-size:12px}}.footer strong{color:var(--black)}.fine{max-width:58ch;order:2}@media(min-width:600px){.fine{order:0}}
    @media(max-width:899px){
      .navlinks{
        display:flex;position:fixed;left:0;right:0;top:58px;flex-direction:column;gap:0;padding:8px 16px 16px;border-bottom:1px solid var(--line);background:rgba(255,255,255,.98);backdrop-filter:saturate(1.4) blur(12px);-webkit-backdrop-filter:saturate(1.4) blur(12px);
        transform:translateY(-8px);opacity:0;pointer-events:none;transition:transform 200ms ease,opacity 200ms ease;box-shadow:0 8px 24px rgba(0,0,0,.06);
        max-height:calc(100vh - 58px);overflow:auto;
      }
      @media(min-width:768px){.navlinks{top:64px;max-height:calc(100vh - 64px);padding:8px 24px 20px}}
      .navlinks.open{transform:none;opacity:1;pointer-events:auto}
      .navlinks a{padding:14px 4px;border-bottom:1px solid var(--line);font-size:14px;color:var(--black);min-height:48px;display:flex;align-items:center}
      .navlinks a:last-child{border:0}
      .navlinks a:hover{color:var(--grey)}
    }
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important}
"""

import re
# Replace content between <style> and </style>
new_html = re.sub(r'<style>.*?</style>', f'<style>{new_css}\n  </style>', html, flags=re.DOTALL)
p.write_text(new_html, encoding='utf-8')
print("CSS updated")
# Also update header to wrap nav-actions
old_header = '<nav class="navlinks" id="navlinks"><a href="#menu">La carte</a><a href="#maison">L’esprit maison</a><a href="#venir">Nous trouver</a></nav><a class="call" href="tel:0769715620">Commander ↗</a><button class="cart-toggle" id="cartToggle" aria-label="Ouvrir le panier">Panier <span class="badge" id="cartCount">0</span></button><button class="toggle" id="toggle" aria-label="Ouvrir la navigation" aria-expanded="false">☰</button>'
new_header = '<nav class="navlinks" id="navlinks"><a href="#menu">La carte</a><a href="#maison">L’esprit maison</a><a href="#venir">Nous trouver</a></nav><div class="nav-actions"><a class="call" href="tel:0769715620">Commander ↗</a><button class="cart-toggle" id="cartToggle" aria-label="Ouvrir le panier">Panier <span class="badge" id="cartCount">0</span></button><button class="toggle" id="toggle" aria-label="Ouvrir la navigation" aria-expanded="false">☰</button></div>'
if old_header in new_html:
    new_html2 = new_html.replace(old_header, new_header)
    p.write_text(new_html2, encoding='utf-8')
    print("Header updated")
else:
    print("Header not found - already updated or mismatch")
    # debug print snippet
    import pathlib as pl
    snippet = new_html[new_html.find('navlinks'):new_html.find('navlinks')+500]
    print(snippet)
